# Generated by Django 5.0.4 on 2024-04-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_core", "0002_post_created_at_post_creator_post_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
